kind: pipeline
name: default

steps:
- name: docker-build
  image: plugins/docker
  settings:
    repo: orlea/aaliyah
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
